name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: staging
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install
        npm install -g @angular/cli
    - name: Public URL
      run: export PUBLIC_URL=https://zearkiatos.github.io/fall-nursery-web/
    - name: Create .env
      run: |
        touch .env &&
        echo "NODE_ENV=${NODE_ENV}" > .env &&
        echo "NG_CLI_ANALYTICS=${NG_CLI_ANALYTICS}" >> .env &&
        echo "PORT=${PORT}" >> .env
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        PORT: ${{ secrets.PORT }}
        NG_CLI_ANALYTICS: ${{ secrets.NG_CLI_ANALYTICS }}
    - name: Test 🧪
      run: npm run test:ci
    - name: Build docker 🐳
      run: docker build . -t=fall-nursery-web:build-$GITHUB_RUN_NUMBER
    - name: Build
      run: npm run deploy
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./dist/fall-nursery-web

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./dist/fall-nursery-web

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/fall-nursery-web
